pipelines:
  branches:
   main:
    - step: 
        name: Deploy to test
        deployment: test
        script:
          - pipe: microsoft/azure-static-web-apps-deploy:dev/stable-branch
            variables:
                APP_LOCATION: '/'
                OUTPUT_LOCATION: '/build'